version: '3.8'
services: 
  node-webpack-vue:
    restart: always 
    build: 
      context: .
      dockerfile: ./images/Dockerfile
    volumes: 
      - /app/node_modules
      - ./www:/app 
    ports: 
      - "3010:3000"
      - "8010:8080"
